events {}

http {
  upstream websocket_backend {
    ip_hash;
    server ws-service-1:8081;
    server ws-service-2:8081;
  }

  server {
    listen 80;

    location /socket.io/ {
      proxy_pass http://websocket_backend;
      proxy_http_version 1.1;

      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}